### ISSUE TITLE
Add option for custom headers or uuid for X-Github-Delivery

### ISSUE THREAD

**Issue by jamengual** [distributhor/workflow-webhook#33]
Usually regular github webhook send the `X-Github-Delivery` header with a UUID as a value and applications that integrate with github webhooks usually check for such value.

I did not see a way to modify the creation of a uuid or to send a custom request header with the uuid.

example of request from a webhook in github:

```Request method: POST
Accept: */*
content-type: application/json
User-Agent: GitHub-Hookshot/5ab4b44
X-GitHub-Delivery: 11eb8e80-3f7f-11ed-8e05-b5a152a893a5
X-GitHub-Event: pull_request```

**Comment by distributhor** [comment]
I have create a new release, which resulted in a new major version (Because the data submitted on the X-GitHub-Delivery changed), though functionally there is no change. You can use the v3 tag to start using it. I've had to make some additional changes to the pull request, since the event name was not consistently handled throughout. The header would reflect the custom name, but not the actual data that was submitted, where the event name generated by Github was still reflected. If a custom name is specified it will now be handled everywhere, as opposed to the Github event name.

**Comment by jamengual** [comment]
awesome, thanks
