### ISSUE TITLE
v3.0.4 generates invalid signature

### ISSUE THREAD

**Issue by stefandesu** [distributhor/workflow-webhook#47]
I've noticed that our webhook that uses this action stopped working. After some investigation, I've found out that the signature is not valid anymore. Testing with the Docker image directly, I've found that it works with v3.0.3, but not in v3.0.4. I assume it is related to [the changes in entrypoint.sh](https://github.com/distributhor/workflow-webhook/compare/v3.0.3...v3.0.4#diff-6f9d41d046756f0ddc2fcee0626bdb50100d12b88f293734eff742818e03efa2).

We're using our homemade https://github.com/gbv/github-webhook-handler for handling webhooks from GitHub. The signature validation code is [here](https://github.com/gbv/github-webhook-handler/blob/1e4988cace729d8bb9980e6cb77399ac067edd59/index.js#L126) and it works perfectly for webhook requests coming directly from GitHub.

**Comment by distributhor** [comment]
Thank you for this feedback. I will look into it today.

**Comment by distributhor** [comment]
I am just busy going through some testing, and things work fine when running through my test cases. In order to help with debugging, and potential issues, I would like to clarify (and possibly suggest an improvement) to the code you reference (referenced below) for validating a signature ...

`const sig = secret && "sha1=" + crypto.createHmac("sha1", secret).update(JSON.stringify(req.body)).digest("hex")`

The snippet stringifies the JSON body, instead of working with the raw body. Can you perhaps try the following and see if it works:

Instead of `app.use(bodyParser.json())`, replace it with:

```
app.use(bodyParser.json({
  verify: (req, res, buf, encoding) => {
    if (buf && buf.length) {
      req.rawBody = buf.toString(encoding || 'utf8');
    }
  },
}))
```

The raw body will then be available on `req.rawBody`, which you can use instead of a stringified `req.body` in the signature verification method:

`const sig = secret && "sha1=" + crypto.createHmac("sha1", secret).update(req.rawBody).digest("hex")`

If you can let me know how that goes, then I can determine whether to take further steps on my side.

**Comment by stefandesu** [comment]
It does indeed work with the raw body. I don't remember where exactly I got that code snippet from, but I was able to find both solutions ([using the raw body](https://gist.github.com/stigok/57d075c1cf2a609cb758898c0b202428) like you suggested and [stringifying req.body](https://humanwhocodes.com/snippets/2020/08/validate-github-webhook-signature-nodejs/)). I see that using the raw body makes more sense and I will change our code accordingly.

Thanks for looking into it!

**Comment by distributhor** [comment]
Awesome, glad it sorted!

**Comment by kgryte** [comment]
We also discovered this bug. The change for from `v3.0.3` to `v3.0.4` resulted in signature verification failures. As mentioned by @stefandesu in the OP, using `request.body` works when verifying requests directly from GitHub, but now fails when sent via this action.

Using the `request.body` is as documented in the [GitHub docs](https://docs.github.com/en/webhooks/using-webhooks/securing-your-webhooks#typescript-example).
